DROP DATABASE Registro;
CREATE DATABASE Registro;
USE Registro;

CREATE TABLE Persona (
ci INT PRIMARY KEY,
Nom_completo VARCHAR(100) NOT NULL,
contraseña VARCHAR(10) NOT NULL,
ubicacion VARCHAR(100) NOT NULL
);

CREATE TABLE proveedor(
ci2 INT PRIMARY KEY,
id_p INT PRIMARY KEY NOT NULL,
nombre_c VARCHAR(40) NOT NULL,
contraseña_p VARCHAR(10) NOT NULL,
contacto INT NOT NULL,
disponibilidad VARCHAR(10) NOT NULL,
CONSTRAINT FOREIGN KEY(ci2) REFERENCES Persona (ci)
);

CREATE TABLE servicio(
id_s VARCHAR(20) PRIMARY KEY,
descripcion VARCHAR(100) NOT NULL
);

CREATE TABLE hace(
id_se VARCHAR(20) PRIMARY KEY NOT NULL,
id_pr INT PRIMARY KEY NOT NULL,
ci3 INT PRIMARY KEY NOT NULL,
precio INT NOT NULL,
horario VARCHAR(20) NOT NULL,
zona VARCHAR(20) NOT NULL,
CONSTRAINT FOREIGN KEY(id_se) REFERENCES servicio (id_s),
CONSTRAINT FOREIGN KEY(id_pr) REFERENCES proveedor (ci2),
CONSTRAINT FOREIGN KEY(ci3) REFERENCES Persona (ci)
);

CREATE TABLE contrata(
ci4 INT PRIMARY KEY NOT NULL,
id_pro INT PRIMARY KEY NOT NULL,
id_ser VARCHAR(20) PRIMARY KEY NOT NULL,
fecha_c VARCHAR(20) NOT NULL,
hora_tra VARCHAR(20) NOT NULL,
CONSTRAINT FOREIGN KEY(ci4) REFERENCES Persona (ci),
CONSTRAINT FOREIGN KEY(id_pro) REFERENCES proveedor (id_p),
CONSTRAINT FOREIGN KEY(id_ser) REFERENCES servicio (id_s)
);

CREATE TABLE horario (
id_h VARCHAR(20) PRIMARY KEY NOT NULL,
fecha_hor_in VARCHAR(10) NOT NULL,
fecha_hor_fin VARCHAR(10) NOT NULL,
estado VARCHAR(10) NOT NULL,
id_prove INT NOT NULL,
CONSTRAINT FOREIGN KEY(id_prove) REFERENCES proveedor (ci2)
);